### ISSUE TITLE
Fixed range for colormap

### ISSUE THREAD

**Issue by TheUser0571** [Biomedical-Imaging-Group/interactive-kit#6]
Specifying `clip_range` when calling the `imviewer `with extra widgets only applies the range clipping to image that the `imviewer `is called with. When the extra widget is used to modify the image, the range clipping is reset to `[min, max]` of the modified image.

**Comment by poldap** [comment]
I will close this issue once we all have a clear idea on the fixes in 345281922860a6341a10f8f1a29be9647a8ee84d

**Comment by Alejandro-1996** [comment]
Relevant to this issue, the changes are in lines 361, 389-395 and 1046 (Ctrl+f range_fixed will quickly highlight the changes). Basically, a variable created to track whether the range was clipped (valid only for original images, and the clipping is not kept when applying transformations) or fixed (the range is kept after applying transformations)
